dist: focal

language: go

go:
  - "1.18.3"
  - tip

matrix:
  allow_failures:
    - go: tip

notifications:
  email: false
  slack:
    secure: c0Rh3jvd9NeSjVqO5w4Ls6Of7Pm1V/RNLUQEK/mcDNYA3Pjy7h+gwWF4Dunw0oZ/AkwXkQMbsL9xrdgtqGBPKzvS/3eo8trOt8cFxdJGDZy7WuQvepRVrK4bFyYZB8dJtY0EdzOODQBpqs7FPDzrxJEml5mXiuizPAFSQtPhWw6AdO6vF+9qJhiDGmIU2d6YeHbT4nZYNxhAfkyrxZoecgu9ilg6zzh5s1mF8P6kLkJCjHgNiuSY4ZeFP+TXbjig5WhbD970xtsPOjZn4CiEiLkCzLyhf8osByDX6V2ZJihwxf4warqGtB3sbIPfyasThyjg0ntoXqQCz8t0uOBmOSPvfuxDj1iM3zSBE+p674f5BOek4mURbRKGNBtTHG64DiryQJKkZOJwFkyKwZQt7yQRAGSUINsjf7aNr7nRKKFRUTD55QJ01q6S2MI+BbBQ4Sdfsgm5gYtoeWatyMiFU1y/iWe6Wsuc5rbQ/1mVtyZec5QYv58YKDs1HbnsQaBTaf4qgHrH6KRIgV5CnVeWg/NSAn19GYYSbdNnHqXlgyWm0E3VSFImqR8Voqsi/1XqsZifvd2VEWzr65ff7ZtLMA872dgRyeYzuQRvcgQc70GO3mpDkgDBTh1rJwIv7twYs5Q/DJqV93CmjIZ85Wa/IZ+fzC5ycSi/htZ8lm/jWkc=
